### ISSUE TITLE
Dev Workflow Inconsistencies

### ISSUE THREAD

**Issue by kahkoii** [np-devops-team1/DevOps_Main#20]
Currently, the "**CI for UnitTest**" workflow in the `CI_DEV.yml` file for developers runs only on push to main, which happens very inconsistently. The workflow file should instead be modified to run on [push] to any branch. Also, currently the tests in the "**Python Program Quality Control**" workflow in the `qualitycheck.yaml` file overlap with the dev workflow actions, so these 2 workflows can be merged into 1 accordingly.

Proposed changes for developers:
1. Rename the workflow in CI_DEV from "CI for UnitTest" to "CI for Dev Unit Tests"
2. Change "CI for Dev Unit Tests" workflow trigger from 
```yaml
on:
  push:
    branches: [main]
```
to
```yaml
on: [push, pull_request]
```

3. Merge "Python Program Quality Control" into the new "CI for Dev Unit Tests" workflow (by adding flake8 test)

**Comment by iamgruuten** [comment]
noted, thanks for the feedback
