### ISSUE TITLE
Pytests carrying over variable states from previously executed tests

### ISSUE THREAD

**Issue by calebanana** [np-devops-team1/DevOps_Main#36]
# Context

When running one of the QA tests, it has been suspected that Pytest has been carrying over variable states from previously executed tests (See explanation below).

![image](https://user-images.githubusercontent.com/47849515/149711568-f774c145-a108-44e1-bea6-5cda18edba5b.png)
In the pytest 3a above, the value of "1" is input into the program, which triggers the "Start New Game" functionality. This supposedly creates a new game instance. After performing checks on the console output, two "0"s are inputted which will end the current program.

![image](https://user-images.githubusercontent.com/47849515/149711937-9b959965-d4d6-4690-a4b1-bf47e33456ee.png)
In pytest 4, the Start Game function is invoked and its output is captured to see if it matches that of the requirements.
However, in this test (which is run after pytest 3), an AssertionError is raised when trying to find the output of "Turn:  1".  Upon closer inspection (see image below), it was noticed that the current turn number was 2 instead of 1 despite exiting the program in pytest 3a and starting a new game in pytest 4.
![image](https://user-images.githubusercontent.com/47849515/149713731-a7886d39-be44-4f96-bb93-9ecb04819f61.png)

As such, it has been speculated that the value for turn number is brought over from previously executed test cases. To confirm these findings, a duplicate of pytest 4 has been created at the start of the test script, and a passing result was obtained.
![image](https://user-images.githubusercontent.com/47849515/149714204-9f2c66dd-41cf-4802-a793-00720a281344.png)

As no instances of a game was started before this test, the turn number was correctly set with a value of 1, hence passing the test case.

**Comment by kahkoii** [comment]
Interesting find, did not expect Pytest to behave this way. I think it could be because of the global variables being used. Perhaps [this link](https://stackoverflow.com/a/55229276) could solve this isssue, specifically option 2, which suggests using `pytest-xdist` to run each test as a new process.

**Comment by kahkoii** [comment]
For now, we can make use of pytest.assume instead when there are more than 1 assert statements.  Apparently, it is not good practice to have several assert statements in 1 test case.
